name: npm-test Workflow

on:
  push:
    branches: [ dev ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node 20
        uses: actions/checkout@v3 #Action que copia o codigo pra unidade do Job      
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Run Npm Test script
        run: npm run test
      